"""Config Profile A — "Champion" (the known-good baseline).

This is the original tuning configuration. It serves as the control
in A/B experiments. Do NOT edit this file when experimenting — make
changes in config_b.py (the challenger) instead.

All balance weights, card tiers, and strategy parameters live here
so they can be tweaked between runs without editing logic code.
"""

from __future__ import annotations


# Enemies that respawn or split on death (e.g. medium slimes → 2 small slimes).
# Killing these doesn't remove threats, so kill_bonus should be suppressed.
RESPAWNING_ENEMIES: frozenset[str] = frozenset({
    "EYE_WITH_TEETH",
    "LEAF_SLIME_M",
    "TWIG_SLIME_M",
})

# ---------------------------------------------------------------------------
# Evaluator weights — combat state scoring (character-agnostic)
# ---------------------------------------------------------------------------

EVALUATOR = {
    # Damage scoring — sim experiments show kill_bonus is the #1 lever.
    # Higher values make the solver focus-fire wounded enemies and prioritise
    # removing attackers from the board over partial damage spread.
    "kill_bonus": 50.0,              # Base bonus for killing an enemy (was 35)
    "buff_kill_bonus": 85.0,         # Extra bonus for killing Buff-intent enemies (was 60)
    "strength_kill_bonus_per": 10.0, # Extra per point of enemy Strength on kill (was 8)
    "damage_alive_weight": 3.0,      # Per-HP damage to living enemies (was 2.5)
    "damage_dead_weight": 0.2,       # Per-HP damage on already-dead enemies (was 0.5)
    "kill_proximity_weight": 10.0,   # Bonus scaled by % HP removed (was 5)

    # Enemy threat prioritisation — multiplier on all damage scoring per enemy
    # Base multiplier is 1.0; these ADD to it based on enemy properties
    "threat_buff_intent": 0.6,       # Buff-intent enemies scale danger each turn
    "threat_strength_per": 0.08,     # Per point of enemy Strength
    "threat_attack_damage_per": 0.01, # Per point of incoming damage from this enemy
    "threat_max_hp_per": 0.001,      # Per point of enemy max HP (tankier = more turns alive)
    "threat_status_intent": 0.3,     # StatusCard intent enemies add junk to your deck
    "threat_debuff_intent": 0.2,     # Debuff intent enemies weaken you

    # Block scoring — sim shows block matters more when HP is low.
    # survive_scale archetype: heavy block when threatened, less when safe.
    "effective_block_weight": 2.0,   # Per-point of block vs incoming damage (was 3.0)
    "wasted_block_penalty": 1.5,     # Per-point of over-block (was 0.2)
    "idle_block_weight": 0.1,        # Block value when no attack incoming

    # HP-aware block scaling: block_weight *= 1 + (threshold - hp) * scale
    # Sim: raising threshold to 60 and steepening scale improved survival.
    "hp_block_threshold": 60,        # HP below which block is weighted extra (was 50)
    "hp_block_scale": 0.05,          # Scale factor per HP below threshold (was 0.04)

    # Unblocked damage penalty — must balance: blocking 10 of 40 incoming
    # is nearly worthless, better to kill an attacker to remove 10 permanently
    "unblocked_damage_penalty": 1.2, # Per-point of incoming damage not blocked (was 1.5)
    "lethal_damage_penalty": 500.0,  # Penalty if unblocked damage kills (was 500, sim tested 900 but too scared)

    # Self-damage
    "self_damage_weight": 0.8,       # Penalty per HP lost from own cards

    # Debuffs on enemies — sim: Vulnerable more valuable than we thought,
    # especially in multi-enemy encounters (multiplied across all targets)
    "vulnerable_value": 3.5,         # Per stack of Vulnerable (was 1.5)
    "weak_vs_attack_value": 2.5,     # Per stack of Weak when enemy attacking
    "weak_vs_other_value": 1.0,      # Per stack of Weak otherwise

    # Player buffs — sim: Strength is the #1 scaling mechanic.
    # Multi-hit cards (Twin Strike, Thrash, Whirlwind) benefit per-hit.
    "strength_gained_value": 15.0,   # (was 5.0)
    "dexterity_gained_value": 5.0,   # (was 3.0)

    # Poison scoring (Silent) — Poison on an enemy deals N + (N-1) + ... + 1
    # = N*(N+1)/2 total future damage.  The evaluator computes the marginal
    # triangle-sum damage from newly added stacks (capturing compounding),
    # then multiplies by this discount.  At 1.0, Deadly Poison (5 stacks =
    # 15 marginal dmg) ties Strike (6 dmg × 2.5 = 15) on a clean target,
    # but correctly dominates when stacking (5->10 = 40 pts).  Strike still
    # wins when it can kill (kill_bonus) or vs high-threat enemies (threat
    # multiplier on damage but not poison).
    "poison_future_discount": 1.0,   # Multiplied by marginal triangle-sum damage

    # Energy efficiency — unspent energy is almost always wrong
    "unspent_energy_penalty": 12.0,  # (was 10.0)

    # Card draw — solver can't simulate real draws (empty draw pile),
    # so we add a heuristic value per card drawn. This ensures draw
    # cards like Acrobatics, Backflip, Dagger Throw are included in
    # the plan. The runner then plays them first and re-solves with
    # the real drawn cards.
    "card_draw_value": 7.0,          # Per card drawn — roughly "average card value"

    # 2-ply enemy simulation — after scoring the post-play state,
    # simulate enemy intents resolving and penalize HP loss / lethal.
    # Kept small (0.3) to avoid double-counting with existing block
    # scoring which already accounts for incoming damage heuristically.
    "enemy_sim_discount": 0.3,       # Weight on post-enemy-turn score
}


# ---------------------------------------------------------------------------
# Per-character power values for the evaluator
# ---------------------------------------------------------------------------

POWER_VALUES: dict[str, dict[str, float]] = {
    "ironclad": {
        "Demon Form": 10.0,         # (was 8.0)
        "Barricade": 8.0,           # (was 6.0)
        "Feel No Pain": 8.0,        # (was 4.0) — key exhaust synergy
        "Dark Embrace": 8.0,        # (was 4.0) — key exhaust synergy
        "Metallicize": 5.0,
        "Corruption": 8.0,          # (was 5.0) — exhaust holy trinity
    },
    "silent": {
        "Accuracy": 10.0,           # Doubles Shiv damage — core scaling
        "Infinite Blades": 9.0,     # Guaranteed Shiv each turn
        "Noxious Fumes": 8.0,       # AoE poison every turn — strong scaling
        "Tools of the Trade": 8.0,  # Draw + discard each turn — engine
        "Footwork": 8.0,            # Dexterity scaling — core block power
        "Well-Laid Plans": 7.0,     # Retain best card — critical consistency
        "Serpent Form": 7.0,        # Strong damage output
        "Accelerant": 7.0,          # Poison multiplier
        "Master Planner": 6.0,      # Makes skills Sly
        "Afterimage": 5.0,          # Block on card play
        "Abrasive": 5.0,            # Block + Thorns from Sly
        "Envenom": 4.0,             # Poison on attack damage
    },
}


# ---------------------------------------------------------------------------
# Card tier lists — per character
# Used in advisor prompts to guide card reward decisions
# ---------------------------------------------------------------------------

CARD_TIERS: dict[str, dict[str, list[str]]] = {
    "ironclad": {
        # Based on Mobalytics Ironclad guide + sim experiments.
        # AoE (Thunderclap, Whirlwind) and multi-hit (Twin Strike, Thrash) are
        # more valuable than single-target burst. Offering is the best card in
        # the game. The "holy trinity" (Corruption + Dark Embrace + Feel No Pain)
        # enables the strongest late-game engine.
        "S": [
            "Offering", "Demon Form", "Corruption", "Impervious",
            "Whirlwind", "Inflame", "Feel No Pain", "Dark Embrace",
        ],
        "A": [
            "Thunderclap", "Twin Strike", "Battle Trance", "Shrug It Off",
            "Burning Pact", "Flame Barrier", "Spot Weakness", "Thrash",
            "Pommel Strike", "True Grit", "Barricade", "Rupture",
            "Hemokinesis", "Brand", "Feed", "Pact's End",
        ],
        "B": [
            "Uppercut", "Headbutt", "Iron Wave", "Body Slam",
            "Breakthrough", "Armaments", "Carnage", "Bludgeon",
            "Bloodletting", "Metallicize", "Inferno", "Juggernaut",
        ],
        "avoid": [
            "Anger", "Setup Strike", "Clash", "Flex",
            "Warcry", "Wild Strike", "Reckless Charge",
        ],
    },
    "silent": {
        # Based on Mobalytics Silent guide + 33-run analysis (gen6).
        # Key findings: bot ignores Dash/Backstab/Well-Laid Plans/Leg Sweep/Footwork
        # which are exactly the block scaling and front-loaded damage cards needed
        # to survive Act 1. Archetype commitment is critical — mixed builds die early.
        "S": [
            "Accuracy", "Infinite Blades", "Tools of the Trade",
            "Master Planner", "Knife Trap",
            "Footwork",                   # Dexterity scaling — core block card
            "Well-Laid Plans",            # Retain best card — critical for consistency
            "Dash",                       # 10 damage + 10 block — best Act 1 card
        ],
        "A": [
            "Backstab",                   # 11 free damage turn 1 — huge Act 1 tempo
            "Leg Sweep",                  # 12 damage + 12 block + Weak — top defensive card
            "Leading Strike", "Cloak and Dagger", "Blade Dance",
            "Poisoned Stab", "Deadly Poison", "Acrobatics",
            "Untouchable", "Flick-Flack", "Noxious Fumes",
            "Accelerant", "Calculated Gamble", "Tactician",
            "Burst", "Serpent Form",
            "Dodge and Roll",             # Block now + next turn — good defense
            "Deflect",                    # Free block — never bad
        ],
        "B": [
            "Dagger Throw", "Ricochet", "Prepared", "Reflex",
            "Speedster", "Abrasive", "Haze", "Outbreak",
            "Bubble Bubble", "Mirage", "Fan of Knives",
            "Hidden Daggers", "Finisher", "Afterimage",
            "Catalyst",                   # Only good with heavy Poison commitment
        ],
        "avoid": [
            "Bane", "Slice",
        ],
    },
}


def format_tier_list(character: str = "ironclad") -> str:
    """Format the tier list as a compact string for prompts."""
    tiers = CARD_TIERS.get(character, CARD_TIERS["ironclad"])
    lines = []
    for tier, cards in tiers.items():
        if tier == "avoid":
            lines.append(f"AVOID: {', '.join(cards)}")
        else:
            lines.append(f"{tier}-tier: {', '.join(cards)}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Relic guides — per character
# Helps advisor evaluate relic picks (boss relics, events, shops).
# ---------------------------------------------------------------------------

RELIC_GUIDE: dict[str, dict[str, dict]] = {
    "ironclad": {
        # Based on Mobalytics Ironclad guide + gameplay analysis.
        "top_picks": {
            "note": "Universally strong — take in almost any deck",
            "relics": [
                "Charon's Ashes",     # AoE damage on exhaust — insane with Corruption
                "Tungsten Rod",       # Reduces ALL HP loss by 1 — stacks with everything
                "Paper Krane",        # Weak reduces damage to 60% instead of 75%
                "Ice Cream",          # Unspent energy carries over — enables big turns
                "Mummified Hand",     # Free energy on power play — snowball engine
                "Chemical X",         # +2 to all X-cost cards (Whirlwind!)
                "Demon Tongue",       # Heal on HP-spend cards — amazing with Offering/Bloodletting
                "Tough Bandages",     # Block on discard — great with exhaust & Burning Pact
            ],
        },
        "strength_scaling": {
            "note": "Strong in Strength decks (Demon Form, Inflame, Spot Weakness)",
            "relics": [
                "Brimstone",          # +2 Str to you AND enemies — risk/reward, favors Str decks
                "Ruined Helmet",      # Usually +2 Str — not build-defining but solid
                "Sword of Jade",      # Free 3 Str — always good
                "Vajra",              # +1 Str at combat start
                "Anchor",             # 10 Block turn 1 — buys time to set up Demon Form
                "Horn Cleat",         # 14 Block turn 1 — same idea, even better
                "Permafrost",         # Retain 1 card turn 1 — helps keep key setup cards
            ],
        },
        "block_build": {
            "note": "Strong in Block decks (Barricade, Juggernaut, Body Slam)",
            "relics": [
                "Cloak Clasp",        # Block on empty hand — triggers Juggernaut
                "Fresnel Lens",       # Boosts Block gained from cards
                "Vambrace",           # Works like Unmovable — persistent Block
                "Sai",                # Simple Block generation on attacks
                "Parrying Shield",    # Extra damage from Block surplus
                "Pael's Legion",      # Block that adds up, especially with Barricade
                "Bronze Scales",      # Thorns — good if you can tank hits
                "Self-Forming Clay",  # Block when losing HP — decent safety net
            ],
        },
        "exhaust_engine": {
            "note": "Strong in Exhaust decks (Corruption, Feel No Pain, Dark Embrace)",
            "relics": [
                "Charon's Ashes",     # AoE damage per exhaust — top-tier
                "Forgotten Soul",     # Smaller-scale exhaust synergy
                "Burning Sticks",     # Smaller-scale Dead Branch effect
                "Joss Paper",         # Extra draw on exhaust
                "Tough Bandages",     # Block on discard/exhaust
            ],
        },
        "hp_spend": {
            "note": "Strong with HP-spending cards (Offering, Bloodletting, Hemokinesis)",
            "relics": [
                "Demon Tongue",       # Heal when spending HP — top-tier here
                "Centennial Puzzle",  # Draw on HP loss — often triggers turn 1
                "Self-Forming Clay",  # Block when losing HP
                "Red Skull",          # +3 Str when below 50% HP
            ],
        },
        "avoid": {
            "note": "Relics with downsides that usually aren't worth it",
            "relics": [
                "Philosopher's Stone", # +1 Str to ALL enemies — too dangerous
                "Ectoplasm",          # Can't gain gold — cripples shop pathing
                "Velvet Choker",      # 6-card play limit — ruins exhaust/Corruption
                "Sozu",               # Can't gain potions — potions save runs
            ],
        },
    },
    "silent": {
        # Based on Mobalytics Silent guide.
        "top_picks": {
            "note": "Universally strong — take in almost any Silent deck",
            "relics": [
                "Paper Krane",        # Weak reduces damage to 60% — Silent applies Weak easily
                "Ice Cream",          # Unspent energy carries over — enables big Shiv/combo turns
                "Mummified Hand",     # Free energy on power play — Accuracy/Infinite Blades
                "Tungsten Rod",       # Reduces ALL HP loss by 1
            ],
        },
        "shiv_synergy": {
            "note": "Strong in Shiv decks (Accuracy, Infinite Blades, Blade Dance)",
            "relics": [
                "Shuriken",           # Gain Strength from playing Attacks — Shivs trigger this
                "Kunai",              # Gain Dexterity from playing Attacks — Shivs trigger this
                "Ornamental Fan",     # Gain Block from playing Attacks — Shivs trigger this
                "Nunchaku",           # Gain energy from playing Attacks
                "Ninja Scroll",       # Start combat with 3 Shivs
                "Kusarigama",         # Works with Shiv spam
                "Joss Paper",         # Extra draw on exhaust — Shivs exhaust
            ],
        },
        "poison_synergy": {
            "note": "Strong in Poison decks (Noxious Fumes, Deadly Poison, Catalyst)",
            "relics": [
                "Snecko Skull",       # Extra Poison on application
                "Twisted Funnel",     # Apply Poison at combat start
                "Unsettling Lamp",    # Doubles first Poison hit
                "Anchor",             # 10 Block turn 1 — survive while Poison ramps
                "Horn Cleat",         # 14 Block turn 1 — survive while Poison ramps
                "Captain's Wheel",    # Defensive coverage for slow starts
            ],
        },
        "sly_synergy": {
            "note": "Strong in Sly/discard decks (Tactician, Reflex, Calculated Gamble)",
            "relics": [
                "Tingsha",            # Damage on discard — great with high discard volume
                "Tough Bandages",     # Block on discard — strong cycling defense
                "The Abacus",         # Extra Block generation on shuffle
            ],
        },
        "avoid": {
            "note": "Relics with downsides that hurt Silent",
            "relics": [
                "Velvet Choker",      # 6-card play limit — ruins Shiv spam and Sly cycling
                "Philosopher's Stone", # +1 Str to ALL enemies — Silent has low HP
                "Ectoplasm",          # Can't gain gold — cripples shop pathing
                "Sozu",               # Can't gain potions — potions save runs
            ],
        },
    },
}


def format_relic_guide(character: str = "ironclad") -> str:
    """Format the relic guide as a compact string for prompts."""
    guide = RELIC_GUIDE.get(character, RELIC_GUIDE["ironclad"])
    lines = []
    for category, info in guide.items():
        label = category.replace("_", " ").upper()
        relic_names = [r.split("  ")[0] for r in info["relics"]]  # strip comments
        lines.append(f"{label} ({info['note']}): {', '.join(relic_names)}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Per-character config — key cards, removal priorities, etc.
# ---------------------------------------------------------------------------

CHARACTER_CONFIG: dict[str, dict] = {
    "ironclad": {
        "key_card": "Bash",
        "key_card_reason": "it's your only source of Vulnerable (50% more damage)",
        "removal_priority": ["Strike", "Defend"],
    },
    "silent": {
        "key_card": "Survivor",
        "key_card_reason": "it enables Sly discards and provides Block",
        "protect_cards": ["Survivor", "Neutralize"],  # Never remove/transform these
        "removal_priority": ["Strike", "Defend"],     # Strikes first — they dilute draws
    },
}


# ---------------------------------------------------------------------------
# Strategy parameters — advisor behavior (character-agnostic)
# ---------------------------------------------------------------------------

STRATEGY = {
    # Deck size thresholds
    "deck_lean_target": 12,          # Ideal deck size
    "deck_warn_threshold": 15,       # "Too large" warning

    # HP thresholds for map decisions
    "hp_critical_pct": 0.35,         # MUST avoid combat
    "hp_low_pct": 0.55,              # Avoid elites
    "hp_elite_min_pct": 0.75,        # Should take elites above this

    # Rest site thresholds
    "rest_heal_threshold": 0.40,     # Rest if HP% below this
    "rest_upgrade_threshold": 0.70,  # Upgrade if HP% above this
    "boss_rest_threshold": 0.70,     # Always rest before boss if below this

    # Shop behavior
    "auto_remove_at_shop": True,     # Auto-remove cards when affordable
    "shop_max_advisor_calls": 3,     # Max LLM calls per shop visit

    # Boss floors (for pre-boss logic)
    "boss_floors": {15, 16, 33, 34, 51, 52},
}


def detect_character(state: dict) -> str:
    """Extract character key from game state. Defaults to 'ironclad'."""
    run = state.get("run") or {}
    name = (run.get("character_name") or run.get("character_id") or "").lower()
    if "silent" in name:
        return "silent"
    if "ironclad" in name:
        return "ironclad"
    return "ironclad"
