"""Build uber-decks-v1 encounter set.

Design goals:
  - Union lean-decks-v1 + draw-synergy-v1 (base coverage)
  - Add gap-filler decks for cards under 20% coverage in existing sets
  - Recalibrate HP for all encounters to target 50% WR against reanalyse-v3 g88

Usage:
    PYTHONIOENCODING=utf-8 python scripts/build_uber_decks.py \\
        --output experiments/_benchmark/encounter_sets/uber-decks-v1.jsonl \\
        --checkpoint C:/coding-projects/sts2-reanalyse-v3/sts2-solver/experiments/reanalyse-v3/betaone_gen88.pt

Outputs:
    {output}           — the encounter set in JSONL
    {output}.audit.txt — coverage audit report
"""
from __future__ import annotations

import argparse
import json
import random
import sys
import tempfile
from collections import Counter
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

import torch

import sts2_engine

from sts2_solver.betaone.deck_gen import build_random_deck, lookup_card
from sts2_solver.betaone.network import (
    BetaOneNetwork, export_onnx, network_kwargs_from_meta,
)

_REPO = Path(__file__).resolve().parents[2]
_DATA = _REPO / "STS2-Agent" / "mcp_server" / "data" / "eng"
_SOLVER_ROOT = _REPO / "sts2-solver" / "src" / "sts2_solver"


# ---------------------------------------------------------------------------
# Eval-required cards that need coverage (from scripts/audit of eval.py)
# ---------------------------------------------------------------------------

EVAL_REQUIRED_CARDS = set("""
ACCELERANT ACCURACY ACROBATICS ADRENALINE BACKFLIP BLADE_DANCE BLUR BULLET_TIME
BURST CALCULATED_GAMBLE CLOAK_AND_DAGGER DAGGER_SPRAY DAGGER_THROW DEADLY_POISON
DEFEND_SILENT DODGE_AND_ROLL ESCAPE_PLAN EXPOSE FINISHER FOOTWORK GRAND_FINALE
HIDDEN_DAGGERS INFECTION INFINITE_BLADES MALAISE NEUTRALIZE NOXIOUS_FUMES
OMNISLICE PIERCING_WAIL PREDATOR PREPARED REFLEX SKEWER STORM_OF_STEEL
STRIKE_SILENT SUCKER_PUNCH SURVIVOR TACTICIAN TOOLS_OF_THE_TRADE UNTOUCHABLE
WELL_LAID_PLANS WRAITH_FORM
""".split())

# Cards generated by effects (status, not deck-built), exclude from coverage targets
STATUS_CARDS = {"SHIV", "SLIMED", "WOUND"}


# Gap-filler specs: (core_cards, count, label)
# Counts bumped on high-skip specs based on v1 attempt:
#   - survivor_dodge: ~45% skip, bump 40 → 80
#   - predator: ~58% skip, bump 40 → 100
#   - omnislice: 100% failed pre-fix (colorless, now fixed), use 80 for safety
# INFECTION removed: it's color=status, only appears in hand via enemy effects;
# eval scenarios test hand-injection handling, not deck composition.
GAP_FILLER_SPECS = [
    (["SURVIVOR", "DODGE_AND_ROLL"], 80,  "survivor_dodge"),
    (["WRAITH_FORM"],                40,  "wraith_form"),
    (["EXPOSE"],                     40,  "expose"),
    (["PIERCING_WAIL", "MALAISE"],   40,  "malaise_wail"),
    (["OMNISLICE"],                  80,  "omnislice"),
    (["PREDATOR"],                   100, "predator"),
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_encounter_set(path: Path) -> list[dict]:
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


def encounter_dedup_key(enc: dict) -> tuple:
    """Dedup by deck (frozenset of card-id multiset) + enemies + relics."""
    deck = enc.get("deck", [])
    card_ids = tuple(sorted((c.get("id") if isinstance(c, dict) else c) for c in deck))
    enemies = tuple(enc.get("enemies", []))
    relics = tuple(sorted(enc.get("relics", [])))
    return (card_ids, enemies, relics)


def load_game_data() -> tuple[str, str]:
    """Returns (monster_json, profiles_json) as strings for FFI."""
    monsters_raw = json.loads((_DATA / "monsters.json").read_text(encoding="utf-8"))
    monsters = {
        m["id"]: {
            "name": m.get("name", m["id"]),
            "min_hp": m.get("min_hp") or 20,
            "max_hp": m.get("max_hp") or 20,
        }
        for m in monsters_raw if m.get("id")
    }
    profiles = json.loads((_SOLVER_ROOT / "enemy_profiles.json").read_text(encoding="utf-8"))
    return json.dumps(monsters), json.dumps(profiles)


def load_card_vocab(ckpt_path: Path) -> tuple[dict, str]:
    """Card vocab from the checkpoint's own dir (preserves alignment with ONNX)."""
    cv = json.loads((ckpt_path.parent / "card_vocab.json").read_text(encoding="utf-8"))
    return cv, json.dumps(cv)


def export_ckpt_onnx(ckpt_path: Path, out_dir: Path) -> str:
    """Export ONNX from .pt checkpoint."""
    out_dir.mkdir(parents=True, exist_ok=True)
    ckpt = torch.load(str(ckpt_path), map_location="cpu", weights_only=False)
    cv = json.loads((ckpt_path.parent / "card_vocab.json").read_text(encoding="utf-8"))
    kwargs = network_kwargs_from_meta(ckpt.get("arch_meta"))
    net = BetaOneNetwork(num_cards=len(cv), **kwargs)
    net.load_state_dict(ckpt["model_state_dict"])
    net.eval()
    return export_onnx(net, str(out_dir))


def calibrate_hp(
    enemies: list[str], deck: list[dict], relics: list[str],
    monster_json: str, profiles_json: str, card_vocab_json: str,
    onnx_path: str, sims: int = 50, combats: int = 32,
) -> int | None:
    """Binary search on HP targeting 50% WR. Returns HP or None if uncalibratable."""
    relics_list = [relics] * combats
    lo, hi = 15, 70
    best_hp = None
    best_diff = 1.0

    for _ in range(6):
        mid = (lo + hi) // 2
        r = sts2_engine.betaone_mcts_selfplay(
            encounters_json=json.dumps([enemies] * combats),
            decks_json=json.dumps([deck] * combats),
            player_hp=mid, player_max_hp=70, player_max_energy=3,
            relics_json=json.dumps(relics_list), potions_json="[]",
            monster_data_json=monster_json,
            enemy_profiles_json=profiles_json,
            onnx_path=onnx_path, card_vocab_json=card_vocab_json,
            num_sims=sims, temperature=0.0,
            seeds=list(range(combats)),
            add_noise=False,
        )
        wins = sum(1 for o in r["outcomes"] if o == "win")
        wr = wins / max(len(r["outcomes"]), 1)
        diff = abs(wr - 0.5)
        if diff < best_diff:
            best_diff = diff
            best_hp = mid

        if wr > 0.55:
            hi = mid - 1
        elif wr < 0.45:
            lo = mid + 1
        else:
            break
        if lo > hi:
            break

    # Reject uncalibratable (couldn't get close to 50%)
    if best_hp is None or best_diff > 0.30:
        return None
    return best_hp


# ---------------------------------------------------------------------------
# Main construction
# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--output", required=True, type=Path)
    p.add_argument("--checkpoint", required=True, type=Path,
                   help="Path to v3 g88 .pt")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--sims", type=int, default=50)
    p.add_argument("--combats", type=int, default=32)
    p.add_argument("--sets", nargs="+", default=["lean-decks-v1", "draw-synergy-v1"],
                   help="Base encounter sets to union")
    args = p.parse_args()

    rng = random.Random(args.seed)

    print("=" * 70)
    print("build_uber_decks_v1")
    print("=" * 70)

    # --- Load base sets ---
    es_dir = _REPO / "sts2-solver" / "experiments" / "_benchmark" / "encounter_sets"
    base_encounters: list[dict] = []
    for name in args.sets:
        path = es_dir / f"{name}.jsonl"
        if not path.exists():
            print(f"  warning: {name} not found at {path}")
            continue
        encs = load_encounter_set(path)
        base_encounters.extend(encs)
        print(f"  loaded {name}: {len(encs)} encounters")

    # Dedup
    seen = set()
    deduped = []
    for e in base_encounters:
        k = encounter_dedup_key(e)
        if k not in seen:
            seen.add(k)
            deduped.append(e)
    print(f"  union deduped: {len(deduped)} unique encounters")

    # --- Gap-filler generation ---
    # Collect enemy + relic pools from base for sampling
    enemy_pool = [tuple(e.get("enemies", [])) for e in deduped if e.get("enemies")]
    relic_pool = [tuple(sorted(e.get("relics", []))) for e in deduped]

    gap_encounters: list[dict] = []
    for core_cards, count, label in GAP_FILLER_SPECS:
        print(f"\n  generating gap-filler: {label} ({core_cards}) × {count}")
        for i in range(count):
            deck = build_random_deck(rng=rng, core_cards=core_cards)
            enemies = list(rng.choice(enemy_pool))
            relics = list(rng.choice(relic_pool))
            gap_encounters.append({
                "enemies": enemies,
                "deck": deck,
                "hp": 50,  # placeholder, will be overwritten by calibration
                "relics": relics,
                "_gap_label": label,
            })

    print(f"\n  total before calibration: {len(deduped) + len(gap_encounters)} encounters")

    # --- Export ONNX from checkpoint ---
    print(f"\n  exporting ONNX from {args.checkpoint.name}...")
    onnx_dir = Path(tempfile.gettempdir()) / "uber_decks_onnx"
    onnx_path = export_ckpt_onnx(args.checkpoint, onnx_dir)
    print(f"  ONNX: {onnx_path}")

    # Load game data
    monster_json, profiles_json = load_game_data()
    card_vocab, card_vocab_json = load_card_vocab(args.checkpoint)

    # --- Calibrate all encounters ---
    all_encounters = deduped + gap_encounters
    calibrated: list[dict] = []
    print(f"\n  calibrating {len(all_encounters)} encounters against v3 g88 (50% WR target)...")
    import time
    t0 = time.time()
    for i, enc in enumerate(all_encounters):
        hp = calibrate_hp(
            enemies=enc["enemies"],
            deck=enc["deck"],
            relics=enc.get("relics", []),
            monster_json=monster_json,
            profiles_json=profiles_json,
            card_vocab_json=card_vocab_json,
            onnx_path=onnx_path,
            sims=args.sims, combats=args.combats,
        )
        if hp is None:
            continue
        out = {
            "enemies": enc["enemies"],
            "deck": enc["deck"],
            "hp": hp,
            "relics": enc.get("relics", []),
        }
        if "_gap_label" in enc:
            out["_gap_label"] = enc["_gap_label"]
        calibrated.append(out)

        # Progress per-encounter so we can watch live
        elapsed = time.time() - t0
        rate = (i + 1) / elapsed
        eta = (len(all_encounters) - (i + 1)) / max(rate, 0.001)
        print(f"    [{i+1}/{len(all_encounters)}] hp={hp}  "
              f"{len(calibrated)}/{i+1} kept  "
              f"{elapsed/60:.1f}m elapsed  ETA {eta/60:.1f}m",
              flush=True)

    # --- Write output ---
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        for enc in calibrated:
            # Strip internal fields from final output
            clean = {k: v for k, v in enc.items() if not k.startswith("_")}
            f.write(json.dumps(clean) + "\n")
    print(f"\n  wrote {len(calibrated)} encounters to {args.output}")

    # --- Coverage audit ---
    audit_path = args.output.with_suffix(".audit.txt")
    card_counts = Counter()
    for enc in calibrated:
        ids = {c.get("id") if isinstance(c, dict) else c for c in enc.get("deck", [])}
        for cid in ids:
            card_counts[cid] += 1

    n = len(calibrated)
    lines = [f"Coverage audit: {args.output.name}", f"n = {n} encounters", ""]
    lines.append(f"{'card':25} | {'count':>6} | {'pct':>6}")
    lines.append("-" * 50)
    gap_count = 0
    for card in sorted(EVAL_REQUIRED_CARDS - STATUS_CARDS):
        c = card_counts.get(card, 0)
        pct = c / n * 100
        flag = " ← GAP" if pct < 20 else ""
        if pct < 20:
            gap_count += 1
        lines.append(f"{card:25} | {c:>6} | {pct:>5.1f}%{flag}")
    lines.append("")
    lines.append(f"gaps (<20% coverage): {gap_count} of {len(EVAL_REQUIRED_CARDS - STATUS_CARDS)}")
    audit_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  coverage audit → {audit_path}")
    print()
    print("\n".join(lines[-5:]))


if __name__ == "__main__":
    main()
