"""Supervised student training from a distillation dataset.

Trains a cold-start BetaOneNetwork on (state, MCTS_policy, MCTS_value) targets
generated by distill_generate.py. Pure policy CE + value MSE, no self-play.

Usage:
    python -m scripts.distill_train \\
        --dataset experiments/distill-v1/dataset.pkl \\
        --output experiments/distill-v1 \\
        --epochs 100 \\
        --batch-size 512
"""
from __future__ import annotations

import argparse
import json
import os
import pickle
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from sts2_solver.betaone.network import (
    BetaOneNetwork,
    STATE_DIM,
    ACTION_DIM,
    MAX_ACTIONS,
    MAX_HAND,
    network_kwargs_from_meta,
)


def _kwargs_for_v3_match():
    """Student matches v3 g88 arch: vhl=3, trunk 2x128, dot_product policy."""
    return dict(
        value_head_layers=3,
        trunk_layers=2,
        trunk_hidden=128,
        policy_head_type="dot_product",
        policy_mlp_hidden=64,
    )


def _policy_ce_loss(logits: torch.Tensor, targets: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
    """Cross-entropy where targets are soft distributions (MCTS visits).

    Note: network.forward() already masks invalid positions to -1e9 via
    masked_fill(action_mask, -1e9), where action_mask True = invalid slot.
    We don't re-mask here; targets are 0 on invalid so those terms vanish.
    """
    log_probs = F.log_softmax(logits, dim=-1)
    loss = -(targets * log_probs).sum(dim=-1).mean()
    return loss


def _value_mse_loss(pred: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    return F.mse_loss(pred, targets)


def _top1_accuracy(logits: torch.Tensor, targets: torch.Tensor, mask: torch.Tensor) -> float:
    """Fraction of states where argmax(logits) == argmax(targets).
    Both logits (via network masking) and targets (zero on invalid) already
    handle the invalid-action positions correctly for argmax.
    """
    pred = logits.argmax(dim=-1)
    true = targets.argmax(dim=-1)
    return (pred == true).float().mean().item()


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--dataset", required=True, help="Path to dataset.pkl")
    p.add_argument("--output", required=True, help="Output dir for checkpoints")
    p.add_argument("--epochs", type=int, default=100)
    p.add_argument("--batch-size", type=int, default=512)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--value-coef", type=float, default=1.0)
    p.add_argument("--val-frac", type=float, default=0.05)
    p.add_argument("--save-every", type=int, default=5)
    p.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    args = p.parse_args()

    sys.stdout.reconfigure(encoding="utf-8")
    os.makedirs(args.output, exist_ok=True)

    # Load dataset
    print(f"Loading {args.dataset}...")
    with open(args.dataset, "rb") as f:
        data = pickle.load(f)
    meta = data.get("meta", {})
    N = len(data["states"])
    print(
        f"Dataset: {N} states from {meta.get('n_encounters', '?')} encounters × "
        f"{meta.get('seeds_per_encounter', '?')} seeds at MCTS-{meta.get('num_sims', '?')}"
    )

    # Build card vocab for student (match teacher's num_cards — comes from dataset meta
    # via the teacher ckpt; but we also need the vocab JSON file for eval later).
    # For training we just need num_cards from any one ckpt-derived source.
    # Parse the teacher's card_vocab size from the generate run.
    num_cards = 578  # v3 g88 / lean-decks-v1 default; TODO: store in dataset meta
    teacher_ckpt_path = meta.get("teacher_checkpoint")
    if teacher_ckpt_path and os.path.exists(teacher_ckpt_path):
        tc = torch.load(teacher_ckpt_path, map_location="cpu", weights_only=False)
        num_cards = tc.get("num_cards", num_cards)

    # Student network — cold start, v3-matching arch
    kw = _kwargs_for_v3_match()
    network = BetaOneNetwork(num_cards=num_cards, **kw).to(args.device)
    print(f"Student: {network.param_count():,} params, vhl={kw['value_head_layers']}")

    # Tensors once
    def _to_t(k, dtype=None):
        arr = data[k]
        t = torch.from_numpy(arr)
        if dtype is not None:
            t = t.to(dtype)
        return t

    states = _to_t("states", torch.float32)
    act_feat = _to_t("action_features", torch.float32)
    act_masks = _to_t("action_masks", torch.bool)
    hand_ids = _to_t("hand_card_ids", torch.long)
    action_ids = _to_t("action_card_ids", torch.long)
    target_policies = _to_t("target_policies", torch.float32)
    target_values = _to_t("target_values", torch.float32)

    # Train/val split (random)
    rng = np.random.RandomState(42)
    idx = rng.permutation(N)
    n_val = max(1, int(N * args.val_frac))
    val_idx = torch.from_numpy(idx[:n_val])
    train_idx = torch.from_numpy(idx[n_val:])
    print(f"Train: {len(train_idx)} | Val: {len(val_idx)}")

    optimizer = torch.optim.Adam(network.parameters(), lr=args.lr)

    history_path = os.path.join(args.output, "distill_history.jsonl")
    open(history_path, "a").close()  # touch

    for epoch in range(1, args.epochs + 1):
        t0 = time.time()
        network.train()
        # Shuffle train indices each epoch
        shuf = train_idx[torch.randperm(len(train_idx))]
        n_batches = (len(shuf) + args.batch_size - 1) // args.batch_size
        train_pol = 0.0
        train_val = 0.0
        train_top1 = 0.0
        steps = 0
        for bi in range(n_batches):
            bs = shuf[bi * args.batch_size : (bi + 1) * args.batch_size]
            s = states[bs].to(args.device)
            af = act_feat[bs].to(args.device)
            am = act_masks[bs].to(args.device)
            hi = hand_ids[bs].to(args.device)
            ai = action_ids[bs].to(args.device)
            tp = target_policies[bs].to(args.device)
            tv = target_values[bs].to(args.device)

            logits, value = network(s, af, am, hi, ai)
            value = value.squeeze(-1)
            pol_loss = _policy_ce_loss(logits, tp, am)
            val_loss = _value_mse_loss(value, tv)
            loss = pol_loss + args.value_coef * val_loss

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            train_pol += pol_loss.item()
            train_val += val_loss.item()
            train_top1 += _top1_accuracy(logits.detach(), tp, am)
            steps += 1

        train_pol /= steps
        train_val /= steps
        train_top1 /= steps

        # Validation
        network.eval()
        with torch.no_grad():
            val_pol = 0.0
            val_val = 0.0
            val_top1 = 0.0
            v_steps = 0
            for bi in range((len(val_idx) + args.batch_size - 1) // args.batch_size):
                bs = val_idx[bi * args.batch_size : (bi + 1) * args.batch_size]
                s = states[bs].to(args.device)
                af = act_feat[bs].to(args.device)
                am = act_masks[bs].to(args.device)
                hi = hand_ids[bs].to(args.device)
                ai = action_ids[bs].to(args.device)
                tp = target_policies[bs].to(args.device)
                tv = target_values[bs].to(args.device)
                logits, value = network(s, af, am, hi, ai)
                value = value.squeeze(-1)
                val_pol += _policy_ce_loss(logits, tp, am).item()
                val_val += _value_mse_loss(value, tv).item()
                val_top1 += _top1_accuracy(logits, tp, am)
                v_steps += 1
            val_pol /= max(v_steps, 1)
            val_val /= max(v_steps, 1)
            val_top1 /= max(v_steps, 1)

        dt = time.time() - t0
        print(
            f"Epoch {epoch:3d}: "
            f"train pol={train_pol:.4f} val={train_val:.4f} top1={train_top1:.3f} | "
            f"val pol={val_pol:.4f} val={val_val:.4f} top1={val_top1:.3f} | "
            f"{dt:.1f}s",
            flush=True,
        )

        with open(history_path, "a", encoding="utf-8") as f:
            f.write(json.dumps({
                "epoch": epoch,
                "train_pol_loss": train_pol,
                "train_val_loss": train_val,
                "train_top1": train_top1,
                "val_pol_loss": val_pol,
                "val_val_loss": val_val,
                "val_top1": val_top1,
                "time_s": dt,
                "timestamp": time.time(),
            }) + "\n")

        if epoch % args.save_every == 0 or epoch == args.epochs:
            ckpt_path = os.path.join(args.output, f"student_epoch{epoch}.pt")
            torch.save({
                "gen": epoch,  # reuse 'gen' for eval harness compat
                "epoch": epoch,
                "arch_meta": network.arch_meta(),
                "model_state_dict": network.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "num_cards": num_cards,
                "distill_meta": meta,
            }, ckpt_path)
            # Also save as latest for eval compat
            latest_path = os.path.join(args.output, "betaone_latest.pt")
            torch.save(torch.load(ckpt_path, map_location="cpu", weights_only=False), latest_path)
            print(f"  saved {ckpt_path}")


if __name__ == "__main__":
    main()
